name: test tf code
on:
  pull_request:
    types: [opened, reopened]

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: eu-central-1
  BUDGET_AMOUNT: '0.01'

jobs: 
  linting:
    name: Code Style Check
    runs-on: ubuntu-latest
    container: "hashicorp/terraform:1.4"
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Check formatting
        run: terraform fmt -check --recursive -diff .

  plan:
    name: Create Terraform Plan
    runs-on: ubuntu-latest
    container: "hashicorp/terraform:1.4"
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v2 #checkout робить pull репозиторію та гілки, в якому запущений. Таким чином, ми отримуємо доступ до коду.
      - name: Tf init
        run: terraform init
      - name: Run tf plan
        run: terraform plan -var "budget_amount=$BUDGET_AMOUNT" -input=false
